### ISSUE TITLE
Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array

### ISSUE THREAD

**Issue by mydnic** [dimsav/laravel-translatable#291]
Hello @dimsav 

I think that since a latest framework update, a new bug appears, and it is quite critical.

The full Stack Trace is below. Code Example is here https://github.com/mydnic/Laravel-Multilingual-SEO-Example.
I basically get this error when seeding my database.

Thanks for helping

```
[2016-11-08 10:54:03] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 660 in /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:118
Stack trace:
#0 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(660): Illuminate\Database\Grammar->parameterize('2016-11-08 10:5...')
#1 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(678): Illuminate\Database\Query\Grammars\Grammar->compileInsert(Object(Illuminate\Database\Query\Builder), Array)
#2 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2148): Illuminate\Database\Query\Grammars\Grammar->compileInsertGetId(Object(Illuminate\Database\Query\Builder), Array, 'id')
#3 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#4 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1451): call_user_func_array(Array, Array)
#5 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1607): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#6 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1576): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1472): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#8 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/dimsav/laravel-translatable/src/Translatable/Translatable.php(229): Illuminate\Database\Eloquent\Model->save(Array)
#9 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(562): App\Post->save()
#10 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/database/seeds/PostsTableSeeder.php(21): Illuminate\Database\Eloquent\Model::create(Array)
#11 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(39): PostsTableSeeder->run()
#12 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/database/seeds/DatabaseSeeder.php(14): Illuminate\Database\Seeder->call('PostsTableSeede...')
#13 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): DatabaseSeeder->run()
#14 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2280): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#15 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure))
#16 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#17 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#18 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#19 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}
```

**Comment by dimsav** [comment]
Hi @mydnic 

please try to find what line of code causes the issue.

**Comment by mydnic** [comment]
@dimsav The stack trace indicated `#10 /home/vagrant/Code/Laravel-Multilingual-SEO-Example/database/seeds/PostsTableSeeder.php(21): Illuminate\Database\Eloquent\Model::create(Array)`

So here https://github.com/mydnic/Laravel-Multilingual-SEO-Example/blob/master/database/seeds/PostsTableSeeder.php#L21

**Comment by mydnic** [comment]
@dimsav Ok ! 

So I've changed the `parameterize()` from

```
public function parameterize(array $values)
    {
        return implode(', ', array_map([$this, 'parameter'], $values));
    }
```

to

```
public function parameterize($values)
    {
        if (!is_array($values)) {
            dd($values);
        }
        return implode(', ', array_map([$this, 'parameter'], $values));
    }
```

Then I run `db:seed` again and I got this in the terminal : 

```
vagrant@homestead:~/Code/Laravel-Multilingual-SEO-Example$ art db:seed
"2016-11-08 13:29:01"
```

**Comment by dimsav** [comment]
Sorry but this is in seeds, which the translatable doesn't officially support. Feel free to open a pull request + a test with the fix.

**Comment by mydnic** [comment]
@dimsav excuse me but I think it's not only related to the fact the code is in a Seeder Class.

I've jsut tried to add this
```
Post::create([
    'en' => [
        'title' => 'My Awesome Post',
        'content' => 'This is some cool paragraph',
    ],
    'fr' => [
        'title' => 'Mon Super Article',
        'content' => 'Ceci est le contenu stylé de mon article',
    ],
]);
```

to my HomeController@index method
I then access the home page in order to execute the post creation.

I notice that the post is created in the "posts" table but the "post_translations" is empty (no new entries created).

Can you please run basic tests of your package with the latest version of the framework ? It seems that this issue is not related to my usage of your package.

I hope it helps!

**Comment by dimsav** [comment]
I ran the tests with the laravel/framework version 57be173 (updated 3 hours ago) without issues.

https://circleci.com/gh/dimsav/laravel-translatable/26

**Comment by rogerhegland** [comment]
I got the same error - the following was my mistake:

```php
// error
Title::create(
   [
            [ 'de' => [ 'name' => 'Frau' ] ],
        //  ^                           // ^
            [ 'fr' => [ 'name' => 'Madame' ] ],
        //  ^                           // ^
            [ 'it' => [ 'name' => 'Donna' ] ]
        //  ^                           // ^
   ]
);

// works
Title::create(
   [
      'de' => [ 'name' => 'Frau' ],
      'fr' => [ 'name' => 'Madame' ],
      'it' => [ 'name' => 'Donna' ]
   ]
);
```
