### ISSUE TITLE
Keep asking about translation table

### ISSUE THREAD

**Issue by mohamedsabil83** [dimsav/laravel-translatable#494]
I had two tables **stores** and **store_translations**. I delete the second with its model **StoreTranslation** also remove `use Translatable` trait from **Store** model.

When trying to add a new record to **stores** table its keep returns an error with **store_translations** table doesn't exist. why?

![screenshot from 2018-07-09 23-57-05](https://user-images.githubusercontent.com/10126040/42475641-df9826ca-83d3-11e8-85ef-c69691456899.png)

**Comment by Gummibeer** [comment]
Can you please provide the whole stack-trace or in best case the repo/code?

From first shot it looks fine (what you've done) and my idea would be a forgotten use in your base model or not deployed changes. But these are just ideas without any reason.

**Comment by mohamedsabil83** [comment]
This is my **Store** model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    protected $fillable = [
        'store_name',
        'store_country',
        'store_city',
        'store_district',
        'mobile',
        'bank_name',
        'bank_account',
        'bank_iban',
        'store_type',
        'identity_id',
        'identity_no',
        'identity_front',
        'identity_back',
        'logo',
    ];

    /*
     * Relation
     * */

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function identity()
    {
        return $this->belongsTo(Identity::class);
    }

    public function seller()
    {
        return $this->belongsTo(User::class);
    }

    /*
     * Mutator
     * */

    public function setBankNameAttribute($value)
    {
        $this->attributes['bank_name'] = uni_arabic_chars($value);
    }

    public function setStoreNameAttribute($value)
    {
        $this->attributes['store_name'] = uni_arabic_chars($value);
    }
}
```
First, I planned to let **store_name** and **bank_name** translated. Later, I change my mind. So, I delete the **StoreTranslation** model and table then remove `use Translatable` from **Store** model.
When I do that, it's return the above problem shown in picture unless I create an empty **store_translations** table with just **store_name** and it's return works. notes that main **store_translations** table was contain both of **store_name** and **bank_name** but after remove translatable it's just required an empty **store_translations** table with only **store_name** column.
Check all my code and trying clearing cache and views but nothing to prevent this problem happen.

**Comment by Gummibeer** [comment]
Because it looks like a `has`-query could it be that you still have a `unique` validation rule? Or do you use op-cache?
And can you send the full stack-trace - the part I can see is just the illuminate core part that doesn't says anything about the query source.

**Comment by mohamedsabil83** [comment]
which part do you need? controller, request or what? or hole project?

**Comment by mohamedsabil83** [comment]
This is the stack-trace of problem.
```
[2018-07-10 13:00:36] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_name' in 'where clause' (SQL: select count(*) as aggregate from `store_translations` where `store_name` = ابو الافكار للتقنية) {"userId":2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_name' in 'where clause' (SQL: select count(*) as aggregate from `store_translations` where `store_name` = ابو الافكار للتقنية) at /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_name' in 'where clause' at /home/mohamedsabil83/www/axzishop/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_name' in 'where clause' at /home/mohamedsabil83/www/axzishop/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80)
[stacktrace]
#0 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1963): Illuminate\\Database\\Connection->select('select count(*)...', Array, false)
#3 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2362): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2290): Illuminate\\Database\\Query\\Builder->aggregate('count', Array)
#8 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(55): Illuminate\\Database\\Query\\Builder->count()
#9 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(687): Illuminate\\Validation\\DatabasePresenceVerifier->getCount('store_translati...', 'store_name', '\\xD8\\xA7\\xD8\\xA8\\xD9\\x88 \\xD8\\xA7\\xD9\\x84\\xD8\\xA7\\xD9\\x81...', NULL, NULL, Array)
#10 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(365): Illuminate\\Validation\\Validator->validateUnique('store_name', '\\xD8\\xA7\\xD8\\xA8\\xD9\\x88 \\xD8\\xA7\\xD9\\x84\\xD8\\xA7\\xD9\\x81...', Array, Object(Illuminate\\Validation\\Validator))
#11 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(268): Illuminate\\Validation\\Validator->validateAttribute('store_name', 'Unique')
#12 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(293): Illuminate\\Validation\\Validator->passes()
#13 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(305): Illuminate\\Validation\\Validator->fails()
#14 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php(31): Illuminate\\Validation\\Validator->validate()
#15 [internal function]: App\\Http\\Controllers\\Auth\\RegisterController->register(Object(Illuminate\\Http\\Request))
#16 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#17 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('register', Array)
#18 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\RegisterController), 'register')
#19 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#20 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#21 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/mohamedsabil83/www/axzishop/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#46 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#47 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#48 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#49 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/mohamedsabil83/www/axzishop/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/mohamedsabil83/www/axzishop/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 /home/mohamedsabil83/www/axzishop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#71 /home/mohamedsabil83/www/axzishop/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#72 /home/mohamedsabil83/www/axzishop/server.php(21): require_once('/home/mohamedsa...')
#73 {main}
"} 
```

**Comment by Gummibeer** [comment]
I just copy one line - but I was right about the unique validation:
```
#11 vendor/laravel/framework/src/Illuminate/Validation/Validator.php(268):
Illuminate\\Validation\\Validator->validateAttribute('store_name', 'Unique')
```
I have no idea how your rule looks like but I bet that you still have the translation table referenced in this rule.
https://laravel.com/docs/5.6/validation#rule-unique

**Comment by mohamedsabil83** [comment]
HaHa, That's a silly thing from me. I don't know how I missed that.
Thank you for helping.
